/*
 * This file is generated by jOOQ.
 */
package de.hochschule.carrental.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Cars implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String brand;
    private String model;
    private String category;
    private Integer price;
    private Boolean available;

    public Cars() {}

    public Cars(Cars value) {
        this.id = value.id;
        this.brand = value.brand;
        this.model = value.model;
        this.category = value.category;
        this.price = value.price;
        this.available = value.available;
    }

    public Cars(
        String id,
        String brand,
        String model,
        String category,
        Integer price,
        Boolean available
    ) {
        this.id = id;
        this.brand = brand;
        this.model = model;
        this.category = category;
        this.price = price;
        this.available = available;
    }

    /**
     * Getter for <code>cars.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>cars.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>cars.brand</code>.
     */
    public String getBrand() {
        return this.brand;
    }

    /**
     * Setter for <code>cars.brand</code>.
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * Getter for <code>cars.model</code>.
     */
    public String getModel() {
        return this.model;
    }

    /**
     * Setter for <code>cars.model</code>.
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * Getter for <code>cars.category</code>.
     */
    public String getCategory() {
        return this.category;
    }

    /**
     * Setter for <code>cars.category</code>.
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * Getter for <code>cars.price</code>.
     */
    public Integer getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>cars.price</code>.
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * Getter for <code>cars.available</code>.
     */
    public Boolean getAvailable() {
        return this.available;
    }

    /**
     * Setter for <code>cars.available</code>.
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Cars other = (Cars) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.brand == null) {
            if (other.brand != null)
                return false;
        }
        else if (!this.brand.equals(other.brand))
            return false;
        if (this.model == null) {
            if (other.model != null)
                return false;
        }
        else if (!this.model.equals(other.model))
            return false;
        if (this.category == null) {
            if (other.category != null)
                return false;
        }
        else if (!this.category.equals(other.category))
            return false;
        if (this.price == null) {
            if (other.price != null)
                return false;
        }
        else if (!this.price.equals(other.price))
            return false;
        if (this.available == null) {
            if (other.available != null)
                return false;
        }
        else if (!this.available.equals(other.available))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.brand == null) ? 0 : this.brand.hashCode());
        result = prime * result + ((this.model == null) ? 0 : this.model.hashCode());
        result = prime * result + ((this.category == null) ? 0 : this.category.hashCode());
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        result = prime * result + ((this.available == null) ? 0 : this.available.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Cars (");

        sb.append(id);
        sb.append(", ").append(brand);
        sb.append(", ").append(model);
        sb.append(", ").append(category);
        sb.append(", ").append(price);
        sb.append(", ").append(available);

        sb.append(")");
        return sb.toString();
    }
}
