/*
 * This file is generated by jOOQ.
 */
package de.hochschule.carrental.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Contracts implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String customerId;
    private String carId;
    private String beginDate;
    private String endDate;
    private Integer price;

    public Contracts() {}

    public Contracts(Contracts value) {
        this.id = value.id;
        this.customerId = value.customerId;
        this.carId = value.carId;
        this.beginDate = value.beginDate;
        this.endDate = value.endDate;
        this.price = value.price;
    }

    public Contracts(
        String id,
        String customerId,
        String carId,
        String beginDate,
        String endDate,
        Integer price
    ) {
        this.id = id;
        this.customerId = customerId;
        this.carId = carId;
        this.beginDate = beginDate;
        this.endDate = endDate;
        this.price = price;
    }

    /**
     * Getter for <code>contracts.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>contracts.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>contracts.customer_id</code>.
     */
    public String getCustomerId() {
        return this.customerId;
    }

    /**
     * Setter for <code>contracts.customer_id</code>.
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    /**
     * Getter for <code>contracts.car_id</code>.
     */
    public String getCarId() {
        return this.carId;
    }

    /**
     * Setter for <code>contracts.car_id</code>.
     */
    public void setCarId(String carId) {
        this.carId = carId;
    }

    /**
     * Getter for <code>contracts.begin_date</code>.
     */
    public String getBeginDate() {
        return this.beginDate;
    }

    /**
     * Setter for <code>contracts.begin_date</code>.
     */
    public void setBeginDate(String beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * Getter for <code>contracts.end_date</code>.
     */
    public String getEndDate() {
        return this.endDate;
    }

    /**
     * Setter for <code>contracts.end_date</code>.
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    /**
     * Getter for <code>contracts.price</code>.
     */
    public Integer getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>contracts.price</code>.
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Contracts other = (Contracts) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.customerId == null) {
            if (other.customerId != null)
                return false;
        }
        else if (!this.customerId.equals(other.customerId))
            return false;
        if (this.carId == null) {
            if (other.carId != null)
                return false;
        }
        else if (!this.carId.equals(other.carId))
            return false;
        if (this.beginDate == null) {
            if (other.beginDate != null)
                return false;
        }
        else if (!this.beginDate.equals(other.beginDate))
            return false;
        if (this.endDate == null) {
            if (other.endDate != null)
                return false;
        }
        else if (!this.endDate.equals(other.endDate))
            return false;
        if (this.price == null) {
            if (other.price != null)
                return false;
        }
        else if (!this.price.equals(other.price))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.customerId == null) ? 0 : this.customerId.hashCode());
        result = prime * result + ((this.carId == null) ? 0 : this.carId.hashCode());
        result = prime * result + ((this.beginDate == null) ? 0 : this.beginDate.hashCode());
        result = prime * result + ((this.endDate == null) ? 0 : this.endDate.hashCode());
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Contracts (");

        sb.append(id);
        sb.append(", ").append(customerId);
        sb.append(", ").append(carId);
        sb.append(", ").append(beginDate);
        sb.append(", ").append(endDate);
        sb.append(", ").append(price);

        sb.append(")");
        return sb.toString();
    }
}
