/*
 * This file is generated by jOOQ.
 */
package de.hochschule.carrental.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Customers implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String name;
    private String dlNumber;
    private String email;

    public Customers() {}

    public Customers(Customers value) {
        this.id = value.id;
        this.name = value.name;
        this.dlNumber = value.dlNumber;
        this.email = value.email;
    }

    public Customers(
        String id,
        String name,
        String dlNumber,
        String email
    ) {
        this.id = id;
        this.name = name;
        this.dlNumber = dlNumber;
        this.email = email;
    }

    /**
     * Getter for <code>customers.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>customers.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>customers.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>customers.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>customers.dl_number</code>.
     */
    public String getDlNumber() {
        return this.dlNumber;
    }

    /**
     * Setter for <code>customers.dl_number</code>.
     */
    public void setDlNumber(String dlNumber) {
        this.dlNumber = dlNumber;
    }

    /**
     * Getter for <code>customers.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>customers.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Customers other = (Customers) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.dlNumber == null) {
            if (other.dlNumber != null)
                return false;
        }
        else if (!this.dlNumber.equals(other.dlNumber))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.dlNumber == null) ? 0 : this.dlNumber.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Customers (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(dlNumber);
        sb.append(", ").append(email);

        sb.append(")");
        return sb.toString();
    }
}
