/*
 * This file is generated by jOOQ.
 */
package de.hochschule.carrental.jooq.tables.records;


import de.hochschule.carrental.jooq.tables.Cars;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CarsRecord extends UpdatableRecordImpl<CarsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cars.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>cars.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>cars.brand</code>.
     */
    public void setBrand(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cars.brand</code>.
     */
    public String getBrand() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cars.model</code>.
     */
    public void setModel(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cars.model</code>.
     */
    public String getModel() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cars.category</code>.
     */
    public void setCategory(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cars.category</code>.
     */
    public String getCategory() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cars.price</code>.
     */
    public void setPrice(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>cars.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>cars.available</code>.
     */
    public void setAvailable(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>cars.available</code>.
     */
    public Boolean getAvailable() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CarsRecord
     */
    public CarsRecord() {
        super(Cars.CARS);
    }

    /**
     * Create a detached, initialised CarsRecord
     */
    public CarsRecord(String id, String brand, String model, String category, Integer price, Boolean available) {
        super(Cars.CARS);

        setId(id);
        setBrand(brand);
        setModel(model);
        setCategory(category);
        setPrice(price);
        setAvailable(available);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CarsRecord
     */
    public CarsRecord(de.hochschule.carrental.jooq.tables.pojos.Cars value) {
        super(Cars.CARS);

        if (value != null) {
            setId(value.getId());
            setBrand(value.getBrand());
            setModel(value.getModel());
            setCategory(value.getCategory());
            setPrice(value.getPrice());
            setAvailable(value.getAvailable());
            resetChangedOnNotNull();
        }
    }
}
