/*
 * This file is generated by jOOQ.
 */
package de.hochschule.carrental.jooq.tables.records;


import de.hochschule.carrental.jooq.tables.Contracts;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ContractsRecord extends UpdatableRecordImpl<ContractsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>contracts.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>contracts.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>contracts.customer_id</code>.
     */
    public void setCustomerId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>contracts.customer_id</code>.
     */
    public String getCustomerId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>contracts.car_id</code>.
     */
    public void setCarId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>contracts.car_id</code>.
     */
    public String getCarId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>contracts.begin_date</code>.
     */
    public void setBeginDate(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>contracts.begin_date</code>.
     */
    public String getBeginDate() {
        return (String) get(3);
    }

    /**
     * Setter for <code>contracts.end_date</code>.
     */
    public void setEndDate(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>contracts.end_date</code>.
     */
    public String getEndDate() {
        return (String) get(4);
    }

    /**
     * Setter for <code>contracts.price</code>.
     */
    public void setPrice(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>contracts.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContractsRecord
     */
    public ContractsRecord() {
        super(Contracts.CONTRACTS);
    }

    /**
     * Create a detached, initialised ContractsRecord
     */
    public ContractsRecord(String id, String customerId, String carId, String beginDate, String endDate, Integer price) {
        super(Contracts.CONTRACTS);

        setId(id);
        setCustomerId(customerId);
        setCarId(carId);
        setBeginDate(beginDate);
        setEndDate(endDate);
        setPrice(price);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ContractsRecord
     */
    public ContractsRecord(de.hochschule.carrental.jooq.tables.pojos.Contracts value) {
        super(Contracts.CONTRACTS);

        if (value != null) {
            setId(value.getId());
            setCustomerId(value.getCustomerId());
            setCarId(value.getCarId());
            setBeginDate(value.getBeginDate());
            setEndDate(value.getEndDate());
            setPrice(value.getPrice());
            resetChangedOnNotNull();
        }
    }
}
