/*
 * This file is generated by jOOQ.
 */
package de.hochschule.carrental.jooq.tables.records;


import de.hochschule.carrental.jooq.tables.Customers;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomersRecord extends UpdatableRecordImpl<CustomersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>customers.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>customers.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>customers.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>customers.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>customers.dl_number</code>.
     */
    public void setDlNumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>customers.dl_number</code>.
     */
    public String getDlNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>customers.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>customers.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomersRecord
     */
    public CustomersRecord() {
        super(Customers.CUSTOMERS);
    }

    /**
     * Create a detached, initialised CustomersRecord
     */
    public CustomersRecord(String id, String name, String dlNumber, String email) {
        super(Customers.CUSTOMERS);

        setId(id);
        setName(name);
        setDlNumber(dlNumber);
        setEmail(email);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CustomersRecord
     */
    public CustomersRecord(de.hochschule.carrental.jooq.tables.pojos.Customers value) {
        super(Customers.CUSTOMERS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDlNumber(value.getDlNumber());
            setEmail(value.getEmail());
            resetChangedOnNotNull();
        }
    }
}
