/*
 * This file is generated by jOOQ.
 */
package de.hochschule.carrental.jooq.tables.daos;


import de.hochschule.carrental.jooq.tables.Cars;
import de.hochschule.carrental.jooq.tables.records.CarsRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CarsDao extends DAOImpl<CarsRecord, de.hochschule.carrental.jooq.tables.pojos.Cars, String> {

    /**
     * Create a new CarsDao without any configuration
     */
    public CarsDao() {
        super(Cars.CARS, de.hochschule.carrental.jooq.tables.pojos.Cars.class);
    }

    /**
     * Create a new CarsDao with an attached configuration
     */
    public CarsDao(Configuration configuration) {
        super(Cars.CARS, de.hochschule.carrental.jooq.tables.pojos.Cars.class, configuration);
    }

    @Override
    public String getId(de.hochschule.carrental.jooq.tables.pojos.Cars object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Cars> fetchRangeOfId(String lowerInclusive, String upperInclusive) {
        return fetchRange(Cars.CARS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Cars> fetchById(String... values) {
        return fetch(Cars.CARS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public de.hochschule.carrental.jooq.tables.pojos.Cars fetchOneById(String value) {
        return fetchOne(Cars.CARS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<de.hochschule.carrental.jooq.tables.pojos.Cars> fetchOptionalById(String value) {
        return fetchOptional(Cars.CARS.ID, value);
    }

    /**
     * Fetch records that have <code>brand BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Cars> fetchRangeOfBrand(String lowerInclusive, String upperInclusive) {
        return fetchRange(Cars.CARS.BRAND, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>brand IN (values)</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Cars> fetchByBrand(String... values) {
        return fetch(Cars.CARS.BRAND, values);
    }

    /**
     * Fetch records that have <code>model BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Cars> fetchRangeOfModel(String lowerInclusive, String upperInclusive) {
        return fetchRange(Cars.CARS.MODEL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>model IN (values)</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Cars> fetchByModel(String... values) {
        return fetch(Cars.CARS.MODEL, values);
    }

    /**
     * Fetch records that have <code>category BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Cars> fetchRangeOfCategory(String lowerInclusive, String upperInclusive) {
        return fetchRange(Cars.CARS.CATEGORY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>category IN (values)</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Cars> fetchByCategory(String... values) {
        return fetch(Cars.CARS.CATEGORY, values);
    }

    /**
     * Fetch records that have <code>price BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Cars> fetchRangeOfPrice(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Cars.CARS.PRICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>price IN (values)</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Cars> fetchByPrice(Integer... values) {
        return fetch(Cars.CARS.PRICE, values);
    }

    /**
     * Fetch records that have <code>available BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Cars> fetchRangeOfAvailable(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Cars.CARS.AVAILABLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>available IN (values)</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Cars> fetchByAvailable(Boolean... values) {
        return fetch(Cars.CARS.AVAILABLE, values);
    }
}
