/*
 * This file is generated by jOOQ.
 */
package de.hochschule.carrental.jooq.tables.daos;


import de.hochschule.carrental.jooq.tables.Contracts;
import de.hochschule.carrental.jooq.tables.records.ContractsRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ContractsDao extends DAOImpl<ContractsRecord, de.hochschule.carrental.jooq.tables.pojos.Contracts, String> {

    /**
     * Create a new ContractsDao without any configuration
     */
    public ContractsDao() {
        super(Contracts.CONTRACTS, de.hochschule.carrental.jooq.tables.pojos.Contracts.class);
    }

    /**
     * Create a new ContractsDao with an attached configuration
     */
    public ContractsDao(Configuration configuration) {
        super(Contracts.CONTRACTS, de.hochschule.carrental.jooq.tables.pojos.Contracts.class, configuration);
    }

    @Override
    public String getId(de.hochschule.carrental.jooq.tables.pojos.Contracts object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Contracts> fetchRangeOfId(String lowerInclusive, String upperInclusive) {
        return fetchRange(Contracts.CONTRACTS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Contracts> fetchById(String... values) {
        return fetch(Contracts.CONTRACTS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public de.hochschule.carrental.jooq.tables.pojos.Contracts fetchOneById(String value) {
        return fetchOne(Contracts.CONTRACTS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<de.hochschule.carrental.jooq.tables.pojos.Contracts> fetchOptionalById(String value) {
        return fetchOptional(Contracts.CONTRACTS.ID, value);
    }

    /**
     * Fetch records that have <code>customer_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Contracts> fetchRangeOfCustomerId(String lowerInclusive, String upperInclusive) {
        return fetchRange(Contracts.CONTRACTS.CUSTOMER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>customer_id IN (values)</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Contracts> fetchByCustomerId(String... values) {
        return fetch(Contracts.CONTRACTS.CUSTOMER_ID, values);
    }

    /**
     * Fetch records that have <code>car_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Contracts> fetchRangeOfCarId(String lowerInclusive, String upperInclusive) {
        return fetchRange(Contracts.CONTRACTS.CAR_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>car_id IN (values)</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Contracts> fetchByCarId(String... values) {
        return fetch(Contracts.CONTRACTS.CAR_ID, values);
    }

    /**
     * Fetch records that have <code>begin_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Contracts> fetchRangeOfBeginDate(String lowerInclusive, String upperInclusive) {
        return fetchRange(Contracts.CONTRACTS.BEGIN_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>begin_date IN (values)</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Contracts> fetchByBeginDate(String... values) {
        return fetch(Contracts.CONTRACTS.BEGIN_DATE, values);
    }

    /**
     * Fetch records that have <code>end_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Contracts> fetchRangeOfEndDate(String lowerInclusive, String upperInclusive) {
        return fetchRange(Contracts.CONTRACTS.END_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>end_date IN (values)</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Contracts> fetchByEndDate(String... values) {
        return fetch(Contracts.CONTRACTS.END_DATE, values);
    }

    /**
     * Fetch records that have <code>price BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Contracts> fetchRangeOfPrice(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Contracts.CONTRACTS.PRICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>price IN (values)</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Contracts> fetchByPrice(Integer... values) {
        return fetch(Contracts.CONTRACTS.PRICE, values);
    }
}
