/*
 * This file is generated by jOOQ.
 */
package de.hochschule.carrental.jooq.tables.daos;


import de.hochschule.carrental.jooq.tables.Customers;
import de.hochschule.carrental.jooq.tables.records.CustomersRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomersDao extends DAOImpl<CustomersRecord, de.hochschule.carrental.jooq.tables.pojos.Customers, String> {

    /**
     * Create a new CustomersDao without any configuration
     */
    public CustomersDao() {
        super(Customers.CUSTOMERS, de.hochschule.carrental.jooq.tables.pojos.Customers.class);
    }

    /**
     * Create a new CustomersDao with an attached configuration
     */
    public CustomersDao(Configuration configuration) {
        super(Customers.CUSTOMERS, de.hochschule.carrental.jooq.tables.pojos.Customers.class, configuration);
    }

    @Override
    public String getId(de.hochschule.carrental.jooq.tables.pojos.Customers object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Customers> fetchRangeOfId(String lowerInclusive, String upperInclusive) {
        return fetchRange(Customers.CUSTOMERS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Customers> fetchById(String... values) {
        return fetch(Customers.CUSTOMERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public de.hochschule.carrental.jooq.tables.pojos.Customers fetchOneById(String value) {
        return fetchOne(Customers.CUSTOMERS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<de.hochschule.carrental.jooq.tables.pojos.Customers> fetchOptionalById(String value) {
        return fetchOptional(Customers.CUSTOMERS.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Customers> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Customers.CUSTOMERS.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Customers> fetchByName(String... values) {
        return fetch(Customers.CUSTOMERS.NAME, values);
    }

    /**
     * Fetch records that have <code>dl_number BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Customers> fetchRangeOfDlNumber(String lowerInclusive, String upperInclusive) {
        return fetchRange(Customers.CUSTOMERS.DL_NUMBER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>dl_number IN (values)</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Customers> fetchByDlNumber(String... values) {
        return fetch(Customers.CUSTOMERS.DL_NUMBER, values);
    }

    /**
     * Fetch a unique record that has <code>dl_number = value</code>
     */
    public de.hochschule.carrental.jooq.tables.pojos.Customers fetchOneByDlNumber(String value) {
        return fetchOne(Customers.CUSTOMERS.DL_NUMBER, value);
    }

    /**
     * Fetch a unique record that has <code>dl_number = value</code>
     */
    public Optional<de.hochschule.carrental.jooq.tables.pojos.Customers> fetchOptionalByDlNumber(String value) {
        return fetchOptional(Customers.CUSTOMERS.DL_NUMBER, value);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Customers> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(Customers.CUSTOMERS.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<de.hochschule.carrental.jooq.tables.pojos.Customers> fetchByEmail(String... values) {
        return fetch(Customers.CUSTOMERS.EMAIL, values);
    }
}
