/*
 * This file is generated by jOOQ.
 */
package de.hochschule.carrental.jooq;


import de.hochschule.carrental.jooq.tables.Cars;
import de.hochschule.carrental.jooq.tables.Contracts;
import de.hochschule.carrental.jooq.tables.Customers;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>cars</code>.
     */
    public final Cars CARS = Cars.CARS;

    /**
     * The table <code>contracts</code>.
     */
    public final Contracts CONTRACTS = Contracts.CONTRACTS;

    /**
     * The table <code>customers</code>.
     */
    public final Customers CUSTOMERS = Customers.CUSTOMERS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Cars.CARS,
            Contracts.CONTRACTS,
            Customers.CUSTOMERS
        );
    }
}
