/*
 * This file is generated by jOOQ.
 */
package de.hochschule.carrental.jooq;


import de.hochschule.carrental.jooq.tables.Cars;
import de.hochschule.carrental.jooq.tables.Contracts;
import de.hochschule.carrental.jooq.tables.Customers;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>cars</code>.
     */
    public static final Cars CARS = Cars.CARS;

    /**
     * The table <code>contracts</code>.
     */
    public static final Contracts CONTRACTS = Contracts.CONTRACTS;

    /**
     * The table <code>customers</code>.
     */
    public static final Customers CUSTOMERS = Customers.CUSTOMERS;
}
