/*
 * This file is generated by jOOQ.
 */
package de.hochschule.carrental.jooq.tables;


import de.hochschule.carrental.jooq.DefaultSchema;
import de.hochschule.carrental.jooq.Keys;
import de.hochschule.carrental.jooq.tables.records.CarsRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Cars extends TableImpl<CarsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cars</code>
     */
    public static final Cars CARS = new Cars();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CarsRecord> getRecordType() {
        return CarsRecord.class;
    }

    /**
     * The column <code>cars.id</code>.
     */
    public final TableField<CarsRecord, String> ID = createField(DSL.name("id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>cars.brand</code>.
     */
    public final TableField<CarsRecord, String> BRAND = createField(DSL.name("brand"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>cars.model</code>.
     */
    public final TableField<CarsRecord, String> MODEL = createField(DSL.name("model"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>cars.category</code>.
     */
    public final TableField<CarsRecord, String> CATEGORY = createField(DSL.name("category"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>cars.price</code>.
     */
    public final TableField<CarsRecord, Integer> PRICE = createField(DSL.name("price"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>cars.available</code>.
     */
    public final TableField<CarsRecord, Boolean> AVAILABLE = createField(DSL.name("available"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.BOOLEAN)), this, "");

    private Cars(Name alias, Table<CarsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Cars(Name alias, Table<CarsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cars</code> table reference
     */
    public Cars(String alias) {
        this(DSL.name(alias), CARS);
    }

    /**
     * Create an aliased <code>cars</code> table reference
     */
    public Cars(Name alias) {
        this(alias, CARS);
    }

    /**
     * Create a <code>cars</code> table reference
     */
    public Cars() {
        this(DSL.name("cars"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<CarsRecord> getPrimaryKey() {
        return Keys.CARS__PK_CARS;
    }

    @Override
    public Cars as(String alias) {
        return new Cars(DSL.name(alias), this);
    }

    @Override
    public Cars as(Name alias) {
        return new Cars(alias, this);
    }

    @Override
    public Cars as(Table<?> alias) {
        return new Cars(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Cars rename(String name) {
        return new Cars(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cars rename(Name name) {
        return new Cars(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cars rename(Table<?> name) {
        return new Cars(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cars where(Condition condition) {
        return new Cars(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cars where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cars where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cars where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cars where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cars where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cars where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cars where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cars whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cars whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
