/*
 * This file is generated by jOOQ.
 */
package de.hochschule.carrental.jooq.tables;


import de.hochschule.carrental.jooq.DefaultSchema;
import de.hochschule.carrental.jooq.Keys;
import de.hochschule.carrental.jooq.tables.records.ContractsRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Contracts extends TableImpl<ContractsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>contracts</code>
     */
    public static final Contracts CONTRACTS = new Contracts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractsRecord> getRecordType() {
        return ContractsRecord.class;
    }

    /**
     * The column <code>contracts.id</code>.
     */
    public final TableField<ContractsRecord, String> ID = createField(DSL.name("id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>contracts.customer_id</code>.
     */
    public final TableField<ContractsRecord, String> CUSTOMER_ID = createField(DSL.name("customer_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>contracts.car_id</code>.
     */
    public final TableField<ContractsRecord, String> CAR_ID = createField(DSL.name("car_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>contracts.begin_date</code>.
     */
    public final TableField<ContractsRecord, String> BEGIN_DATE = createField(DSL.name("begin_date"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>contracts.end_date</code>.
     */
    public final TableField<ContractsRecord, String> END_DATE = createField(DSL.name("end_date"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>contracts.price</code>.
     */
    public final TableField<ContractsRecord, Integer> PRICE = createField(DSL.name("price"), SQLDataType.INTEGER.nullable(false), this, "");

    private Contracts(Name alias, Table<ContractsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Contracts(Name alias, Table<ContractsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>contracts</code> table reference
     */
    public Contracts(String alias) {
        this(DSL.name(alias), CONTRACTS);
    }

    /**
     * Create an aliased <code>contracts</code> table reference
     */
    public Contracts(Name alias) {
        this(alias, CONTRACTS);
    }

    /**
     * Create a <code>contracts</code> table reference
     */
    public Contracts() {
        this(DSL.name("contracts"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<ContractsRecord> getPrimaryKey() {
        return Keys.CONTRACTS__PK_CONTRACTS;
    }

    @Override
    public Contracts as(String alias) {
        return new Contracts(DSL.name(alias), this);
    }

    @Override
    public Contracts as(Name alias) {
        return new Contracts(alias, this);
    }

    @Override
    public Contracts as(Table<?> alias) {
        return new Contracts(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Contracts rename(String name) {
        return new Contracts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Contracts rename(Name name) {
        return new Contracts(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Contracts rename(Table<?> name) {
        return new Contracts(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Contracts where(Condition condition) {
        return new Contracts(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Contracts where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Contracts where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Contracts where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Contracts where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Contracts where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Contracts where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Contracts where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Contracts whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Contracts whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
